# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "41c173b5-f055-4e8c-9b15-4fcb3bc0e1ea"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  build_app(
    scheme: "Infinit",
 	export_method: "enterprise"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # api_token: "",
    # build_secret: ""
  )

  slack(
    # slack_url: "",
    # message: "Successfully distributed a new beta build"
  )
end
